### PR TITLE
Add per-map color correction

### PR DESCRIPTION
**Pull request by Triang3l**
This pull request adds support for post-processing color correction lookup tables.

The color correction is set per-map in the `_correction` keyvalue of `worldspawn` (only file name, no path or extension).

On devmaps, the LUT can be overriden with the `r_colorcorrection_force` cvar for testing (but I can change it from `CHEAT` to `ARCHIVE` if we would allow players to use custom LUTs) and reloaded in real time using the `r_colorcorrection_reload` command (this is required since we don't have a built-in tool for color correction, but even if we did, there still should be a preview button).

The effect can be toggled with `r_colorcorrection`. I'm not sure if it should be the default on the medium settings, though.

The `.raw` format is compatible with the Source engine (32x32x32 RGB 3D texture), and the folder where the LUTs should be placed is `correction/`.

### CODE REVIEW

**Comment by viciious** [comment]
Imo changes to r_colorcorrection_force should be automatically detected. The r_colorcorrection_reload cmd seems superfluous.

**Comment by Triang3l** [comment]
@viciious I thought about this. So I guess reload it the same way as the HUD (change to something else, then change back)? And should it be a cheat or archived?

**Comment by Triang3l** [comment]
I'll also rename `_force` to `_override`.

**Comment by viciious** [comment]
Either CVAR_CHEAT or CVAR_DEVELOPER, I guess. No sense in archiving it, imo.

**Comment by Triang3l** [comment]
Does `devmap` enable `CVAR_DEVELOPER`? I guess it should be `CVAR_CHEAT` then.

**Comment by viciious** [comment]
No idea tbh, I guess not.

**Comment by viciious** [comment]
I don't like the word "correction" used without its "color" counterpart
throughout the source (e.g. R_FindCorrectionTexture -> correction for
what?). Besides, "_correction" as entity key looks a bit retarded, needs to
be changed to either "_color_correction" or "_colorcorrection".

2015-03-05 21:53 GMT+03:00 SiPlus notifications@github.com:

> Does devmap enable CVAR_DEVELOPER?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/151#issuecomment-77425609.

## 

Best regards,
 Victor Luchitz

**Pull request merged**
