### PR TITLE
libRocket 1.3.0 binary for OS X

### PR DESCRIPTION
**Pull request by stopiccot**

### CODE REVIEW

**Comment by viciious** [comment]
Btw, it still doesn't work for some reason :(
http://ex60.stopiccot.com:8010/builders/OS%20X

**Comment by stopiccot** [comment]
Yeah i've messed things a bit and committed libc++-linked version instead of libstdc++-linked one.
But i think we can just switch to libc++ in Warsow as libstdc++ is no more updated in OS X sdks.

**Comment by stopiccot** [comment]
It should be finally fixed after merging SDL2 pull request

**Comment by stopiccot** [comment]
Seems to be fixed according to the builder

**Pull request merged**
