### PR TITLE
Use stdint and stdbool on all platforms

### PR DESCRIPTION
**Pull request by stopiccot**
After recent migration to Visual Studio 2013 C99 is now finally available on all platforms so we can safely use stdint and stdbool types. Maybe we should remove qboolean, qint64, .. aliases in future and use bool, int64_t, ... directly? It will make code a bit cleaner.

### CODE REVIEW

**Comment by viciious** [comment]
C99 support in MSVC is only partial...

2014-10-29 14:18 GMT+03:00 Alexey notifications@github.com:

> After recent migration to Visual Studio 2013 C99 is now finally available
> on all platforms so we can safely use stdint and stdbool types. Maybe we
> should remove qboolean, qint64, .. aliases in future and use bool, int64_t,
> 
> ## ... directly? It will make code a bit cleaner.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/stopiccot/qfusion c99
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/Warsow/qfusion/pull/126
> Commit Summary
> - Use stdint and stdbool on all platforms
> 
> File Changes
> - _M_ source/CMakeLists.txt
>   https://github.com/Warsow/qfusion/pull/126/files#diff-0 (1)
> - _M_ source/gameshared/q_arch.h
>   https://github.com/Warsow/qfusion/pull/126/files#diff-1 (32)
> - _M_ source/ref_gl/r_register.c
>   https://github.com/Warsow/qfusion/pull/126/files#diff-2 (2)
> 
> Patch Links:
> - https://github.com/Warsow/qfusion/pull/126.patch
> - https://github.com/Warsow/qfusion/pull/126.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/126.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Ok, it's almost full, and it supports changes in this pull request

**Comment by stopiccot** [comment]
So... this pull request doesn't brake anything on windows because it doesn't use c99 parts that msvc doesn't support. And I'll note one more time that c99 support in Visual Studio 2013 is almost full.

**Comment by viciious** [comment]
I need to make sure this doesn't break the existing MSVC projects first..

2014-11-05 17:49 GMT+03:00 Alexey notifications@github.com:

> So... this pull request doesn't brake anything on windows because it
> doesn't use c99 parts that msvc doesn't support. And I'll note one more
> time that c99 support in Visual Studio 2013 is almost full.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/126#issuecomment-61817539.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
It doesn't

**Comment by stopiccot** [comment]
Btw, where I can get latest development data files? local game menu is not working for me anymore

**Comment by viciious** [comment]
Development files aren't meant for public access since they are WIP, it's
easier to fix the current UI to work with the current source.

2014-11-05 19:51 GMT+03:00 Alexey notifications@github.com:

> Btw, where I can get latest development data files? local game menu is not
> working for me anymore
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/126#issuecomment-61840357.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Any ideas how I can fix local game button? I'm getting error:

```
ScriptEventListener:Not gonna call invalid function __eventfunc_7 void __eventfunc_7(Element @self, Event @event){animOpenMenu('game_local.rml');}
```

**Comment by viciious** [comment]
Might be an UI code bug, I'll look into this.

2014-11-06 0:48 GMT+03:00 Alexey notifications@github.com:

> Any ideas how I can fix local game button? I'm getting error:
> 
> ScriptEventListener:Not gonna call invalid function __eventfunc_7 void __eventfunc_7(Element @self, Event @event){animOpenMenu('game_local.rml');}
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/126#issuecomment-61887223.

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Next time, submit the full stack trace, please:

^5ANGELSCRIPT: _script_5 63:2: Compiling void onJoinShow(Element@, Event@)
^1ERROR: _script_5 74:20: No matching signatures to
'Window::set_location(URL)'
^5ANGELSCRIPT: _script_5 74:20: Candidates are:
^5ANGELSCRIPT: _script_5 74:20: void Window::set_location(const String&in)
^3WARNING: ScriptEventListener::fetchFunctionPtr failed with onJoinLoad
^1ScriptEventListener: Not gonna call invalid function onJoinLoad
$onJoinLoad
^3WARNING: ScriptEventListener::fetchFunctionPtr failed with onJoinShow
^1ScriptEventListener: Not gonna call invalid function onJoinShow
$onJoinShow

You need to edit the line 80 of game_join.rml so it reads as follows:
window.location = location.getURL();

2014-11-06 1:06 GMT+03:00 Victor Luchitz vluchits@gmail.com:

> Might be an UI code bug, I'll look into this.
> 
> 2014-11-06 0:48 GMT+03:00 Alexey notifications@github.com:
> 
> > Any ideas how I can fix local game button? I'm getting error:
> > 
> > ScriptEventListener:Not gonna call invalid function __eventfunc_7 void __eventfunc_7(Element @self, Event @event){animOpenMenu('game_local.rml');}
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Warsow/qfusion/pull/126#issuecomment-61887223.
> 
> ## 
> 
> Best regards,
>  Victor Luchitz

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Thanks for fix. But there more problems. Trying to start local game on any map gives me error:

```
Reason: 'Default Player Model'(bigvic): Skin (models/players/bigvic/default) failed to load
```

**Comment by viciious** [comment]
Dunno what that one is about, to be honest. Looks like corrupt installation
or something.

2014-11-06 3:51 GMT+03:00 Alexey notifications@github.com:

> Thanks for fix. But there more problems. Trying to start local game on any
> map gives me error:
> 
> Reason: 'Default Player Model'(bigvic): Skin (models/players/bigvic/default) failed to load
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/126#issuecomment-61910121.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
It turns out that qfusion built from master ignores *pure.pk3 packages for some reason. Any thoughts on this?

**Comment by viciious** [comment]
Lines 3255-3256 of files.c

2014-11-11 19:16 GMT+03:00 Alexey notifications@github.com:

> It turns out that qfusion built from master ignores *pure.pk3 packages for
> some reason. Any thoughts on this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/126#issuecomment-62571029.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Yeah, that's how I figured that out but I don't understand how this condition works for live warsow versions. Is files.c patched for them?

**Comment by viciious** [comment]
You just need to replace the file qcommon/version.h with version from 1.5
SDK

2014-11-12 3:53 GMT+03:00 Alexey notifications@github.com:

> Yeah, that's how I figured that out but I don't understand how this
> condition works for live warsow versions. Is files.c patched for them?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/126#issuecomment-62652276.

## 

Best regards,
 Victor Luchitz

**Comment by Triang3l** [comment]
version.h from the SDK is somewhat incompatible, you need to use version.warsow.h from the repo.

**Pull request merged**
