### PR TITLE
Allow vote changing

### PR DESCRIPTION
**Pull request by hettoo**
Funny to see how people who implement something based on a real-world concept sometimes also copy its limitations without realizing they are not features.

Being able to change your vote should be useful if you get persuaded or otherwise change your mind or perhaps even accidentally hit the wrong button.

### CODE REVIEW

**Comment by viciious** [comment]
I'm kinda reluctant to merge this one for two reasons:
1) allowing vote changing is sure going to be abused
2) this somewhat breaks the callvotes menu I have coded for warsow: it relies on the fact that a player can not change the vote and thus disables the voting buttons

**Comment by hettoo** [comment]
How exactly do you think this would be abused?
Just to be sure: this is about changing your vote (yes / no), not the callvote value.

**Comment by viciious** [comment]
Well, there should be a limit on the number of vote changes you can make, otherwise it's going to be a mess with ppl changing votes just to annoy the callers. I know how that happens in warsow community :)

**Comment by hettoo** [comment]
I guess it might happen. Doesn't seem very likely to me because of a combination of the fact that any abuse means you are voting what you do not want to vote for a while (during which the vote might pass) and the effect is not directly noticeable because of the vote state print delay while again others are voting at the same time.
Anyhow, if this also provides difficulty with your menu I'll just close it. Not important at all anyway. ;)

**Comment by viciious** [comment]
Well, I can fix the menu if you implement limiting the number of vote changes :P

**Comment by hettoo** [comment]
Alright, made a cvar for the maximum amount of changes (including the first vote, defaults to 3).
Leaving the decisions for the transmission of the data to you. A player should be able to vote if clientVoteChanges[n] > 0 for his player number n.

Btw, it looks like the clientVoted (and now also clientVoteChanges) array member is not reset when a client connects/disconnects. If player slots are reused quickly this may mean new players inherit the vote state of a previous player.

**Pull request merged**
