### PR TITLE
Ungrab/grab keyboard on focus

### PR DESCRIPTION
**Pull request by kalhartt**
Lets me use window manager binds after opening console.

### CODE REVIEW

**Comment by viciious** [comment]
## Unfortunately, If you ungrab the kb, you won't be able to toggle the console anymore :p

Best regards, 
Victor
понедельник, 31 марта 2014г., 09:36 +0400 from Kalhartt notifications@github.com:

## Lets me use window manager binds after opening console.

You can merge this Pull Request by running
  git pull https://github.com/kalhartt/qfusion kbbind
Or view, comment on, or merge it at:
   https://github.com/viciious/qfusion/pull/61
Commit Summary
*  Ungrab/grab keyboard on focus
File Changes
*  M source/unix/unix_input.c (2)
Patch Links:
*  https://github.com/viciious/qfusion/pull/61.patch
*  https://github.com/viciious/qfusion/pull/61.diff

**Comment by kalhartt** [comment]
Oo really? It rebinds when the window regains focus though, not when console closes. I've only tested in awesomewm and openbox, but I dont have an issue like that.

**Comment by viciious** [comment]
## It worked that way in Unity last time I tried, but I probably need to give this another shot

Best regards, 
Victor
понедельник, 31 марта 2014г., 09:36 +0400 from Kalhartt notifications@github.com:

## Lets me use window manager binds after opening console.

You can merge this Pull Request by running
  git pull https://github.com/kalhartt/qfusion kbbind
Or view, comment on, or merge it at:
   https://github.com/viciious/qfusion/pull/61
Commit Summary
*  Ungrab/grab keyboard on focus
File Changes
*  M source/unix/unix_input.c (2)
Patch Links:
*  https://github.com/viciious/qfusion/pull/61.patch
*  https://github.com/viciious/qfusion/pull/61.diff

**Comment by kalhartt** [comment]
Works as expected on ubuntu 13.10 w/ Unity for me.

**Pull request merged**
