### PR TITLE
Complete demo names

### PR DESCRIPTION
**Pull request by hettoo**
Could be useful when repeatedly watching a demo or if one just can't be bothered to click through the menu.

### CODE REVIEW

**Comment by viciious** [comment]
Nice idea! May I suggest to refactor this code to be slightly more generic to allow TAB-completion for files with certain extension (or all files) in the specified path? For example, 'cinematic' command would benefit from it.

**Comment by hettoo** [comment]
Like this? I'll see if I can implement some other uses tonight.

**Comment by viciious** [comment]
Yes, exactly! Just the header comment section for Cmd_CompleteFileList needs to be fixed now.

**Comment by hettoo** [comment]
Oops, fixed. :p

I was just trying it on the main directory, but it crashes on one of the memmoves. I must be missing something stupid. In the end the remaining size variable seems to be smaller than the actual size of the last element in the list.

**Comment by hettoo** [comment]
Nvm. :D

**Comment by viciious** [comment]
"Nvm" as in "I'm done with this, all bugs are now fixed, feel free to
merge" ? :)

2013/11/19 Gerco van Heerdt notifications@github.com

> Nvm. :D
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/pull/39#issuecomment-28816301
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
Yeah sorry, had to leave.

The game crashes if I try to complete something starting with ./ or ../. I was just experimenting with this on my old version where it did not crash, so perhaps a bug with some new code.
The input should not contain these at all either way.

**Comment by hettoo** [comment]
The exec completion is nice too btw.

I think subdirectories should indeed be at the beginning of the list, because in this case I'm getting loads of directories with only a few config files scattered between them. It would make it a lot easier if the files were at the end.

**Comment by viciious** [comment]
Ye, I'm on it :)

2013/11/20 Gerco van Heerdt notifications@github.com

> The exec completion is nice too btw.
> 
> I think subdirectories should indeed be at the beginning of the list,
> because in this case I'm getting loads of directories with only a few
> config files scattered between them. It would make it a lot easier if the
> files were at the end.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/pull/39#issuecomment-28840883
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
See changes in commit 256308333039975ff2a838f12b915c50c13d937d

2013/11/20 Victor Luchitz vluchits@gmail.com

> Ye, I'm on it :)
> 
> 2013/11/20 Gerco van Heerdt notifications@github.com
> 
> > The exec completion is nice too btw.
> > 
> > I think subdirectories should indeed be at the beginning of the list,
> > because in this case I'm getting loads of directories with only a few
> > config files scattered between them. It would make it a lot easier if the
> > files were at the end.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/pull/39#issuecomment-28840883
> > .
> 
> ## 
> 
> Best regards,
>  Victor Luchitz

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
I didn't get why a NULL extension should force subdirectories. Calling the function with a NULL extension and subdirectories being false I would expect to get all files in the directory, without subdirectory results.

Also, in the unlikely event that a file is added to the directory between the size queries and the actual list retrievals some items will need to be discarded.

The file/subdirectory pass distinction within the pass loop makes the function really complex. :p
I've made a function abstraction for the passes here: https://github.com/hettoo/qfusion/blob/filecompletion/source/qcommon/cmd.c#L1042
Do you think this would be better? The function does have a lot of parameters.
This version also applies the above.

**Comment by viciious** [comment]
NULL extension passed to FS_GetFileList returns subdirectories as well, in
this sense, Cmd_CompleteFileList is consistent with that.

As for the refactoring, to be honest, I prefer the current git version.

2013/11/20 Gerco van Heerdt notifications@github.com

> I didn't get why a NULL extension should force subdirectories. Calling the
> function with a NULL extension and subdirectories being false I would
> expect to get all files in the directory, without subdirectory results.
> 
> Also, in the unlikely event that a file is added to the directory between
> the size queries and the actual list retrievals some items will need to be
> discarded.
> 
> The file/subdirectory pass distinction within the pass loop makes the
> function really complex. :p
> I've made a function abstraction for the passes here:
> https://github.com/hettoo/qfusion/blob/filecompletion/source/qcommon/cmd.c#L1042
> Do you think this would be better? The function does have a lot of
> parameters.
> This version also applies the above.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/pull/39#issuecomment-28907551
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
FS_GetFileList does not have a subdirectories boolean which is supposed to define the behavior regarding those subdirectories.

Ok.
This '/0' should be a '\0' btw: https://github.com/viciious/qfusion/blob/master/source/qcommon/cmd.c#L1087

**Comment by viciious** [comment]
Ok, I've altered Cmd_CompleteFileList to work the way you originally
intended. Fixed the typo too.

2013/11/20 Gerco van Heerdt notifications@github.com

> FS_GetFileList does not have a subdirectories boolean which is supposed to
> define the behavior regarding those subdirectories.
> 
> Ok.
> This '/0' should be a '\0' btw:
> https://github.com/viciious/qfusion/blob/master/source/qcommon/cmd.c#L1087
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/pull/39#issuecomment-28921620
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
Thanks. :)

**Pull request merged**
