### PR TITLE
Don't draw RG/MG flesh hit

### PR DESCRIPTION
**Pull request by adem4ik**
RG/MG flesh hit is a client side effect which tends to be incorrect even on low ping - http://screenshotcomparison.com/comparison.php?id=137247

And since it is drawn in red it may look like a bloody hit while there was no hit at all. So the best option is not to draw it at all, especially when there is another hit effect called BloodTrail.

Btw the same solution is used in q3 engine:
shot0005

### CODE REVIEW

**Comment by viciious** [comment]
Maybe it still should be ok to draw it for corpses?

2016-01-04 16:46 GMT+03:00 Andrei Stepanov notifications@github.com:

> RG/MG flesh hit is a client side effect which tends to be incorrect even
> on low ping - http://screenshotcomparison.com/comparison.php?id=137247
> 
> And since it is drawn in red it may look like a bloody hit while there was
> no hit at all. So the best option is not to draw it at all, especially when
> there is another hit effect called BloodTrail.
> 
> Btw the same solution is used in q3 engine:
> [image: shot0005]
> 
> ## https://cloud.githubusercontent.com/assets/4707112/12090731/8da225d6-b302-11e5-9c19-9eab6261c0af.jpg
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Warsow/qfusion/pull/291
> Commit Summary
> - Don't draw RG/MG flesh hit
> 
> File Changes
> - _M_ source/cgame/cg_lents.cpp
>   https://github.com/Warsow/qfusion/pull/291/files#diff-0 (12)
> 
> Patch Links:
> - https://github.com/Warsow/qfusion/pull/291.patch
> - https://github.com/Warsow/qfusion/pull/291.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/291.

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
You're right, i'll update pull request

**Comment by adem4ik** [comment]
Pull request has been updated as suggested.

**Comment by adem4ik** [comment]
pull request has been updated.

**Pull request merged**
