### PR TITLE
Refactoring mac backend to SDL2 backend

### PR DESCRIPTION
**Pull request by stopiccot**
Not ready yet just another small portion. Affects only OS X build. OS X build should be working fine.

### CODE REVIEW

**Comment by vkni** [comment]
Други, я не смогу проверить это еще неделю.

**Comment by viciious** [comment]
Why sdl_sys_osx.m ? It's not even including any of SDL files.

**Comment by stopiccot** [comment]
Eventually SDL backend will work on all platforms. But some things will remain platform specific. So treat this file like "osx platform specific stuff in sdl backend". Of course I can rename to something like sources/mac/mac_sys.m but I dont see much sense in it. In my opinion its better to place all sdl related files in sdl folder.

**Comment by viciious** [comment]
There's nothing SDL specific in that file so I believe it belongs to mac/ instead of sdl/

**Comment by stopiccot** [comment]
Ok, fixed that

**Comment by stopiccot** [comment]
Anything else preventing from merge?

**Comment by Triang3l** [comment]
`unix/unix_snd.c` should be `sdl/sdl_snd.c` now, I think.

**Pull request merged**
