### PR TITLE
New +forward acceleration for cg_movementStyle 1

### PR DESCRIPTION
**Pull request by stylemistake**
New implementation of +forward acceleration

* Now uses aircontrol (as in old movement)
* Adds acceleration when looking straight
* Inverse square acceleration reduction

With +forward you accelerate up to 700 almost as fast as with strafe, but after 1100 it becomes very slow. Has no weird side-effets that require a speed limitation. Keeps speed when turning.

**IMPORTANT**: Reverted all movement constants as it was in Warsow 2.1 (normal/dash speed, dash delay).

### CODE REVIEW

**Comment by adem4ik** [comment]
> Reverted all movement constants as it was in Warsow 2.1 (normal/dash speed, dash delay).

Why?

**Comment by stylemistake** [comment]
@adem4ik It would require to rebalance a lot of things in the game, and there was nothing wrong with old constants.

**Comment by stylemistake** [comment]
Or we can split this thing into two separate PRs.

**Comment by dnk777** [comment]
I fully agree on the first part (reverting movement params back to 2.1 values). A Runner has ground speed of 350 units in `ctf:t`, an by making this huge value default one would make all 17 players left quit. 

I am however strongly against any movement changes unless they are reviewed and tested by a master of movement from both in-game and code sides (say @hettoo who has introduced crouchsliding/skimming).

This line is awkward to me:

```
float dot = 50 * ( DotProduct( heading, wishdir ) - 0.98 );
clamp(dot, 0, 1);
```

And also you use arbitrary var declaration inside a block, a thing that is not expected in `gameshared` module unless it is rewritten in C++.

**Comment by adem4ik** [comment]
Actually there were a lot of movement changes since 2.1 - including skimming, sliding, and it is strange to push your changes and using "2.1's balance" as reason for reverting changes from other people. The were reasons of those changes, and people who made it had and aggrement from team members. The whole balance idea is going to be reworked in future. So please lets keep what we had.

**Comment by dnk777** [comment]
A ground speed of 350 units is a joke (it affects proportionally SJ acceleration too). There was already lot of complaints from best players about movement being way too easy.

**Comment by dnk777** [comment]
On crouchsliding/skimming — these additions are minor. Crouchsliding does not let you fly into a room bouncing off walls on high speed.

**Comment by stylemistake** [comment]
> I am however strongly against any movement changes unless they are reviewed and tested by a master of movement from both in-game and code sides.

Keep in mind, that this is a non-default movement style. I highly doubt that somebody liked `cg_movementStyle 1` in version `>=1.5`.

The only thing that might be bad with this movement style: it can be abused to reach higher speeds than you normally would with `cg_movementStyle 0`, because you can easily combine it with usual strafejumping _(strafe -> airaccel -> strafe -> airaccel -> bunny -> airaccel, etc...)_.

But in contrast, you lose predictability in jumps, because with `cg_movementStyle 0` you have an advantage of keeping the speed unchanged thoughout the jump, and with `cg_movementStyle 1` you can miss the platform because you accelerated while flying towards it. So it's a double-edged sword.

With `cg_movementStyle 0`, you fly with aircontrol and **without** acceleration.

With `cg_movementStyle 1`, you fly with aircontrol and **with** acceleration.

> And also you use arbitrary var declaration inside a block, a thing that is not expected in gameshared module unless it is rewritten in C++.

Makes sense.

**Pull request merged**
