### PR TITLE
Updated libRocket Framework for OSX.

### PR DESCRIPTION
**Pull request by vkni**
Fonts now work. But for some reason, that is unknown to me, QFusion hangs in couple seconds after start. This is unrelated to libRocket update and possibly results from extremely low FPS (my system is 10 years old).

### CODE REVIEW

**Comment by stopiccot** [comment]
Generally bad idea to touch CMakeLists.txt for no reason. Non-default options values ment to be set via command line while generating project:

```
cmake -G Xcode -DBUILD_FRAMEWORK=1 .
```

**Comment by stopiccot** [comment]
Also it should be probably built with new `BUILD_ROCKET_8BPP_FONTS` option. @viciious should know the answer.

**Comment by viciious** [comment]
Yes, turning that option on would be a good idea.

**Comment by vkni** [comment]
Хорошо, как её включать?

**Comment by stopiccot** [comment]
`cmake -G Xcode -DBUILD_FRAMEWORK=1 -DBUILD_ROCKET_8BPP_FONTS=1 .`

**Comment by vkni** [comment]
Алексей, спасибо!

30.01.2015, 20:15, "Alexey" notifications@github.com:

**Comment by vkni** [comment]
Я эту магию запишу в source/mac/Frameworks/README, если не возражаете. По-английски.

**Pull request closed without merging**
