### PR TITLE
splitting *_sys.c files

### PR DESCRIPTION
**Pull request by stopiccot**
Attempt to modularize things a bit extracting some functionality from *_sys.c files to *_time.c, *_clipboard.c, *_console.c.

### CODE REVIEW

**Comment by viciious** [comment]
Why? This is starting to look like quakeforge.

2015-01-06 1:44 GMT+03:00 Alexey notifications@github.com:

> Attempt to modularize things a bit extracting some functionality from
> 
> ## *_sys.c files to *_time.c, *_clipboard.c, *_console.c.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/stopiccot/qfusion sys_refactoring
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/Warsow/qfusion/pull/132
> Commit Summary
> - splitting *_sys.c files
> 
> File Changes
> - _M_ source/Makefile
>   https://github.com/Warsow/qfusion/pull/132/files#diff-0 (12)
> - _M_ source/client/CMakeLists.txt
>   https://github.com/Warsow/qfusion/pull/132/files#diff-1 (9)
> - _A_ source/null/clipboard_null.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-2 (24)
> - _M_ source/qfusion.sln
>   https://github.com/Warsow/qfusion/pull/132/files#diff-3 (6)
> - _M_ source/qfusion.vcxproj
>   https://github.com/Warsow/qfusion/pull/132/files#diff-4 (3)
> - _M_ source/qfusion.vcxproj.filters
>   https://github.com/Warsow/qfusion/pull/132/files#diff-5 (9)
> - _M_ source/qfusion_server.vcxproj
>   https://github.com/Warsow/qfusion/pull/132/files#diff-6 (3)
> - _M_ source/qfusion_server.vcxproj.filters
>   https://github.com/Warsow/qfusion/pull/132/files#diff-7 (9)
> - _M_ source/qfusiongame.sln
>   https://github.com/Warsow/qfusion/pull/132/files#diff-8 (6)
> - _A_ source/sdl/sdl_clipboard.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-9 (26)
> - _M_ source/sdl/sdl_sys.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-10 (26)
> - _M_ source/server/CMakeLists.txt
>   https://github.com/Warsow/qfusion/pull/132/files#diff-11 (5)
> - _M_ source/tv_server/CMakeLists.txt
>   https://github.com/Warsow/qfusion/pull/132/files#diff-12 (5)
> - _M_ source/tv_server/tv_server.vcxproj
>   https://github.com/Warsow/qfusion/pull/132/files#diff-13 (3)
> - _M_ source/tv_server/tv_server.vcxproj.filters
>   https://github.com/Warsow/qfusion/pull/132/files#diff-14 (9)
> - _A_ source/unix/unix_clipboard.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-15 (100)
> - _A_ source/unix/unix_console.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-16 (119)
> - _M_ source/unix/unix_input.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-17 (99)
> - _M_ source/unix/unix_sys.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-18 (193)
> - _A_ source/unix/unix_time.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-19 (53)
> - _A_ source/win32/win_clipboard.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-20 (83)
> - _A_ source/win32/win_console.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-21 (182)
> - _M_ source/win32/win_sys.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-22 (353)
> - _A_ source/win32/win_time.c
>   https://github.com/Warsow/qfusion/pull/132/files#diff-23 (83)
> 
> Patch Links:
> - https://github.com/Warsow/qfusion/pull/132.patch
> - https://github.com/Warsow/qfusion/pull/132.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/132.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Quakeforge? Main reason is that further SDL development will end up in endless #ifdef USE_SDL2 in *_sys.c files. And separating things is treated a good practice in software development.

**Comment by viciious** [comment]
Yes, quakeforge:
http://sourceforge.net/p/quake/quakeforge/ci/master/tree/libs/

Anyway, my main question is: are you working on a complete SDL2 port?

2015-01-06 2:30 GMT+03:00 Alexey notifications@github.com:

> Quakeforge? Main reason is that further SDL development will end up in
> endless #ifdef USE_SDL2 in *_sys.c files. And separating things is treated
> a good practice in software development.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/132#issuecomment-68801417.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Yeah, i'm currently working on complete SDL2 port that will run on all platforms (Windows/Linux/OSX and maybe even Android). Just trying to deliver it in a series of relatively small pull requests so its easy to review them.

**Comment by adem4ik** [comment]
I have only question: Does SDL2 has touch screens and raw mouse input support? Otherwise that work is pointless.

**Comment by stopiccot** [comment]
Yes, SDL has touch support. Not sure what you mean by raw mouse input support.

**Comment by viciious** [comment]
I belive, by raw input he means this:
https://github.com/Warsow/qfusion/blob/master/source/win32/win_input.c#L535

2015-01-06 15:21 GMT+03:00 Alexey notifications@github.com:

> Yes, SDL has touch support. Not sure what you mean by raw mouse input
> support.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/132#issuecomment-68858781.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Obviously we can keep any platform specific code if needed.

**Comment by adem4ik** [comment]
I mean raw input not only for Windows, but for Linux as well. Wasn't it 1.5 that introduced XInput2 for input and for mouse raw input in particular?

**Comment by stopiccot** [comment]
Dont know. But i can tell you that there was no any raw mouse support for OS X for sure.

**Comment by stopiccot** [comment]
And it seems that SDL both supports Xinput2 for linux, and RegisterRawInputDevices-based input for windows. So basically we are writing here own SDL. That one is really pointless.

**Comment by sundflux** [comment]
SDL has no use for input outside of OS X (which is the only reason why current codebase has SDL at all). Both Linux and Windows have proper raw input, and they work (and are defaults on both since 1.5 iirc). 

(not that I have anything against SDL2, as long as it doesn't break my precious raw input :))

**Comment by stopiccot** [comment]
And even if SDL is missing some bits of functionality it's always better to send them a pull request so all other world can share your code. In return we can use their code. Well tested by big community i must note.

**Comment by viciious** [comment]
I'm ok with the fullblown transition to SDL2, given there's no
functionality loss.

2015-01-06 17:07 GMT+03:00 Alexey notifications@github.com:

> And even if SDL is missing some bits of functionality it's always better
> to send them a pull request so all other world can share your code. In
> return we can use their code. Well tested by big community i must note.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/pull/132#issuecomment-68868836.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
It's intended to be an option to build an SDL based version so no functionality loss here.

**Comment by stopiccot** [comment]
So taking into account that nobody is against futher SDL development. What about this pull request? I'm ok with ifdefs but I thought it's better to split things.

**Comment by Triang3l** [comment]
Android will have separate sys code, by the way, to use things like nonlinear depth and stereo on Tegra, wake locks, DPI scaling.

**Comment by viciious** [comment]
12>win32\win_sys.c(141): warning C4013: 'Sys_InitTime' undefined; assuming extern returning int
12>win32\win_sys.c(497): warning C4013: 'Sys_Milliseconds_TGT' undefined; assuming extern returning int
12>win32\win_sys.c(498): warning C4013: 'Sys_Microseconds_QPC' undefined; assuming extern returning int

**Comment by adem4ik** [comment]
I'm not sure, but mb i should post it here too:

> Compiling unix/unix_vid.c
> unix/unix_console.c: In function ‘Sys_ConsoleInput’:
> unix/unix_console.c:29:2: warning: implicit declaration of function ‘read’ [-Wimplicit-function-declaration]
>   len = read( 0, text, sizeof( text ) );
>   ^
> Compiling null/clipboard_null.c
> unix/unix_console.c: In function ‘Sys_ConsoleInput’:
> unix/unix_console.c:29:2: warning: implicit declaration of function ‘read’ [-Wimplicit-function-declaration]
>   len = read( 0, text, sizeof( text ) );
>   ^

**Comment by stopiccot** [comment]
about win_sys.c warnings it seems this is caused by static modifier on those functions. I'll fix that

**Comment by viciious** [comment]
No, it's seems that win_sys.c got not clue on them because they are not declared anywhere.

**Pull request merged**
