### PR TITLE
Added some score events and client method for use in gametype scripts.

### PR DESCRIPTION
**Pull request by DenMSC**
"shot" score_event, triggers when a shot is fired.
"chat" score_event, triggers when someone chats.
Client.get_pressedKeys(), returns bitmask of buttons being pressed.

### CODE REVIEW

**Comment by viciious** [comment]
I'm not convinced that passing weapon shots as score events would be appropriate.
More importantly, you forgot to explain the purpose of the changes.

**Comment by DenMSC** [comment]
These are some things that i've wanted to use in gametype scripts, but ended up having to resort to weird and unreliable ways of detecting shots for example. The purpose is pretty much to give modders more options, if it was up to me and was able to do more, I would add a lot of extra stuff to the gametype script API. These seemed easiest for me to add, and will be very useful for anybody.

**Comment by viciious** [comment]
The G_Gametype_ScoreEvent is a hack which has gone way beyond its original scope and purpose. It should not be used for things like weapon shots and chat messages. Adding specialized AS API calls would be much more appropriate.

**Comment by viciious** [comment]
get_pressedKeys() impelmented in 68bb8990872c4126561c41208fdd0a26ca6a34d9

**Comment by viciious** [comment]
The rest I'm really uncertain of.

**Pull request closed without merging**
