### PR TITLE
Revert "Revert "Include space between previous origin and current ori…

### PR DESCRIPTION
**Pull request by hettoo**
Reverts #175. See #169.

### CODE REVIEW

**Comment by viciious** [comment]
I believe it's important that it's documented why the code has taken its current form and also list its limitations.

**Comment by hettoo** [comment]
Yes, I agree. Would this be ok? I don't know what that "falling damage" comment did there, it has nothing to do with triggers. :p

**Comment by viciious** [comment]
Could you also add a note on trigger loops this code might cause?

**Comment by viciious** [comment]
Is there a way we can possibly check for teleportation and _not_ consider the old position in such case?

**Comment by hettoo** [comment]
Note that the code does not really cause the trigger loops. Instead, it fixes the old situation of not being exact about what triggers were touched. In some way it was a bug that these trigger loops did not happen before. :)
Thus, I don't think a comment about this fits in the code...

We could probably disable trigger_teleports the first frame after a teleport, but I would prefer to see that as a separate feature rather than a part of this.
(Actually, mappers should be discouraged from positioning the target against the trigger, but I take it this would be to ensure compatibility with old q2/q3 maps that may have such a bug.)
Another way is to ignore a tiny gap after the previous origin. That seems even uglier to me...

**Comment by hettoo** [comment]
Ok, maybe actually that second option is better, as we actually should have an open interval at the old origin end. I'll try to add that.
It will allow the 8 unit distance, but nothing much closer. However, I don't think mappers will put it closer.

**Comment by hettoo** [comment]
An open interval is approximated (with a gap of 0.01 units, so only in extremely rare cases can a trigger be skipped, which would have to be very thin too), but the area will at least include the full player at the current position.

I checked that this fixed wdm11 and wctf1. Sorry @sundflux if you put time into fixing them...

**Comment by hettoo** [comment]
Ugh, all this time I failed to realize we should only add the area between the old and new playerboxes, not the old playerbox itself...

Sorry for making a mess of this. The final version is nice, though, in my opinion. It will interact with teles almost the same as the current qfusion.

**Comment by viciious** [comment]
Does the new version still require fixing stock warsow maps?

**Comment by hettoo** [comment]
No, it does not. :)

**Pull request merged**
