### PR TITLE
cmake windows

### PR DESCRIPTION
**Pull request by stopiccot**
Сборка cmake-ом на винде. Пришлось переименовать некоторые пресобранные либы, чтоб cmake их находил.

### CODE REVIEW

**Comment by viciious** [comment]
What kind of prob does cmake have finding the *stat.lib files?

2014-06-24 15:44 GMT+04:00 Alexey notifications@github.com:

> Сборка cmake-ом на винде. Пришлось переименовать некоторые пресобранные
> 
> ## либы, чтоб cmake их находил.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/stopiccot/qfusion cmake_windows
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/viciious/qfusion/pull/106
> Commit Summary
> - renaming prebuilt windows libs so cmake can find them
> - fixing current visual studio projects
> - Initial cmake windows commit
> 
> File Changes
> - _M_ source/CMakeLists.txt
>   https://github.com/viciious/qfusion/pull/106/files#diff-0 (71)
> - _M_ source/client/CMakeLists.txt
>   https://github.com/viciious/qfusion/pull/106/files#diff-1 (45)
> - _M_ source/cmake/FindRocket.cmake
>   https://github.com/viciious/qfusion/pull/106/files#diff-2 (9)
> - _M_ source/ftlib/ftlib.vcxproj
>   https://github.com/viciious/qfusion/pull/106/files#diff-3 (4)
> - _M_ source/irc/CMakeLists.txt
>   https://github.com/viciious/qfusion/pull/106/files#diff-4 (6)
> - _M_ source/qfusion.vcxproj
>   https://github.com/viciious/qfusion/pull/106/files#diff-5 (4)
> - _M_ source/qfusion_server.vcxproj
>   https://github.com/viciious/qfusion/pull/106/files#diff-6 (4)
> - _M_ source/ref_gl/CMakeLists.txt
>   https://github.com/viciious/qfusion/pull/106/files#diff-7 (9)
> - _M_ source/ref_gl/ref_gl.vcxproj
>   https://github.com/viciious/qfusion/pull/106/files#diff-8 (4)
> - _M_ source/snd_openal/CMakeLists.txt
>   https://github.com/viciious/qfusion/pull/106/files#diff-9 (6)
> - _M_ source/snd_qf/CMakeLists.txt
>   https://github.com/viciious/qfusion/pull/106/files#diff-10 (19)
> - _M_ source/tv_server/CMakeLists.txt
>   https://github.com/viciious/qfusion/pull/106/files#diff-11 (36)
> - _M_ source/tv_server/tv_server.vcxproj
>   https://github.com/viciious/qfusion/pull/106/files#diff-12 (4)
> - _R_ source/win32/x86/lib/debug/curllib_static.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-13 (0)
> - _R_ source/win32/x86/lib/debug/jpeg.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-14 (0)
> - _R_ source/win32/x86/lib/debug/libfreetype.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-15 (0)
> - _R_ source/win32/x86/lib/debug/png.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-16 (0)
> - _R_ source/win32/x86/lib/debug/zlib.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-17 (0)
> - _R_ source/win32/x86/lib/release/curllib_static.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-18 (0)
> - _R_ source/win32/x86/lib/release/jpeg.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-19 (0)
> - _R_ source/win32/x86/lib/release/libfreetype.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-20 (0)
> - _R_ source/win32/x86/lib/release/png.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-21 (0)
> - _R_ source/win32/x86/lib/release/zlib.lib
>   https://github.com/viciious/qfusion/pull/106/files#diff-22 (0)
> 
> Patch Links:
> - https://github.com/viciious/qfusion/pull/106.patch
> - https://github.com/viciious/qfusion/pull/106.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/pull/106.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
For each library cmake has a list of known names that it will look for.
For example in case of curl it will look for: curl.lib, curllib.lib, libcurl_imp.lib, curllib_static.lib, libcurl.lib
So it will fail to find it with curllib_static.lib name.
Same for all other libs

**Comment by vkni** [comment]
Это как-нибудь затрагивает OSX?

**Comment by stopiccot** [comment]
Нет

**Comment by vkni** [comment]
Други, так в чём проблема с этим pull-request'ом? Почему он и не закрыт, и не слит с основной веткой?

**Comment by viciious** [comment]
проблема в том, что я болел и не разбирался пока с ним. чуть попозже
вернусь.

25 июня 2014 г., 18:59 пользователь Vkni notifications@github.com написал:

> Други, так в чём проблема с этим pull-request'ом? Почему он и не закрыт, и
> не слит с основной веткой?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/pull/106#issuecomment-47112520.

## 

Best regards,
 Victor Luchitz

**Comment by vkni** [comment]
Выздоравливайте!

**Comment by vkni** [comment]
Всё превосходно собирается на OSX, ошибок нет.

**Pull request merged**
