### PR TITLE
Smarter walljump choices

### PR DESCRIPTION
**Pull request by hettoo**
The current walljump code prefers, out of the walls found around the player within a reasonable distance, the wall that is closest to the player. This leads to unpredictable and often undesired results. If two walls are close (for instance because we stand in a corner) it is unclear what wall will be jumped against when a walljump is performed.

Within this reasonable distance, the wall that is to be jumped against should be chosen based on the viewangles and the buttons pressed by the player. The control that is thus added is a new little element that could benefit from some skill, but at the same time it is quite natural.

The proposed check works as follows. There is a primary direction relative to the viewangles that is determined as follows:
- If left is pressed, the direction is to the left of the player's viewangles.
- If right is pressed, it is to the right.
- If forward is pressed, it is in front.
- Otherwise, it is behind.
  The reason for defaulting behind is that after the walljump we should prefer to move forward if possible.

The order of directions in which walls are checked is indicated very roughly here (using 6 directions instead of 12), where the first is the primary direction:
https://dl.dropboxusercontent.com/u/22044693/wjdir.png
The first valid wall that is found is returned.

The traces now use zero vector mins/maxs in order to give us control over the preferred walls. This will not lead to problems unless there are several holes in the walls at unfortunate positions. We could increase the number of checks if necessary.

The old code checked in a circle around the player origin. I took a fixed distance around the player box, which I think is more sensible for collision-like events. I have chosen this distance to mimic the old minimum walljump distance as closely as possible.
The locations are still shifted along to the velocity in order to avoid actual collisions.

### CODE REVIEW

**Comment by viciious** [comment]
I'd like to get this change properly tested as it's a bit too late for inclusion with 2.1

**Comment by hettoo** [comment]
That's ok.

I had one of the racers play around with this, and he quite liked it, but since I rewrote most of the function I see it could use some other people testing it.

Do you mean you want me to get players to test this soon, or would you prefer to skip this until after 2.1? I think I could find one or two more racers, and I also believe adem likes reviewing these kind of things, but the latter option is fine as well.

**Comment by viciious** [comment]
Yeah, I'd prefer to skip this until after 2.1

**Comment by adem4ik** [comment]
I'm on @viciious side, it is quite big change and involves a lot of risks. But I'll test it for sure.

**Comment by hettoo** [comment]
Ok, cool :)

**Comment by adem4ik** [comment]
I won't test it. Warsow development is over for me now.

**Comment by hettoo** [comment]
Note that this hardly changes any "scary" things. It does not affect the way walljump works, but just the selection of the wall that is walljumped against.

I had one of the top racers play around with this, and then the following appeared somewhere in our racesow slack addressed at another player:
wj
What he mentions here is that the difference with the old situation is very small when there is significant velocity. However, when standing in a corner, one can observe that the old code performs very "random" (unpredictable), whereas the new code prefers the wall that is pointed at.
By the way, I actually had ffa and dm in mind when I started on this.

The one tricky part is that in each direction an infinitely small check is performed (a line), which means that if there is an unfortunately positioned tiny wall or a wall with very unfortunate holes, the code will fail to provide a walljump.
This can hardly be called an issue (think of the feet not being able to handle this tiny wall / getting problems with the holes), but as a precaution I have raised the number of directions checks are performed from 12 to 20 (edit: went from 18 to 20 just because it is theoretically more uniform).

As these traces are probably expensive, there is now first a trace that checks the entire area in which the other checks are performed so that these individual checks can be skipped if there is nothing at all.
Note also that the new code returns on the first passing check, whereas the old one always went through all checks.

**Comment by viciious** [comment]
@hettoo Do you think it should be merged now?

**Comment by hettoo** [comment]
I would like that, yes. :)

**Pull request merged**
