### PR TITLE
Initial mingw support for cmake.

### PR DESCRIPTION
**Pull request by stopiccot**
x86 mingw build seems to be working. Need x64 prebuilt binaries to test x64 mingw build. As for windows I needed different names for prebuilt binaries so cmake can find them. But instead of renaming I've created symlinks because I didn't want to touch existing Makefile.

### CODE REVIEW

**Comment by stopiccot** [comment]
It still would be great to have x64 prebuilt binaries for mingw

**Comment by viciious** [comment]
I'm not sure what you mean by "prebuilt binaries".

2014-09-03 19:39 GMT+04:00 Alexey notifications@github.com:

> It still would be great to have x64 prebuilt binaries for mingw
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/pull/114#issuecomment-54316198.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
mostly files located in source/win32/x86/lib/mingw

**Comment by viciious** [comment]
Well, mingw compilation is mostly intended for the buildbot which
automatically copies the libs to appropriate location.

2014-09-03 22:20 GMT+04:00 Alexey notifications@github.com:

> mostly files located in source/win32/x86/lib/mingw
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/pull/114#issuecomment-54342119.

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Another reason I'm not adding mingw libs is that they are ridiculously
huge: iirc libRocket alone needs 200MB of disk space.

2014-09-03 23:58 GMT+04:00 Victor Luchitz vluchits@gmail.com:

> Well, mingw compilation is mostly intended for the buildbot which
> automatically copies the libs to appropriate location.
> 
> 2014-09-03 22:20 GMT+04:00 Alexey notifications@github.com:
> 
> > mostly files located in source/win32/x86/lib/mingw
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/viciious/qfusion/pull/114#issuecomment-54342119.
> 
> ## 
> 
> Best regards,
>  Victor Luchitz

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
But currently folder source/win32/x86/lib/mingw is only 3.24Mb in size

**Comment by viciious** [comment]
Ah, mingw compilation doesn't require precompiled librocket files to work.
Alright then.

2014-09-05 17:57 GMT+04:00 Alexey notifications@github.com:

> But currently folder source/win32/x86/lib/mingw is only 3.24Mb in size
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/pull/114#issuecomment-54627927.

## 

Best regards,
 Victor Luchitz

**Pull request merged**
