### PR TITLE
Fix fs_game changing from commandline

### PR DESCRIPTION
**Pull request by hettoo**
Fixes the issue discussed at https://github.com/Qfusion/qfusion/commit/e9c43b4b1816a5b74323cabb2a176ec524b93304.

### CODE REVIEW

**Comment by viciious** [comment]
Mind moving variable declaration into the respective block? :)

**Comment by hettoo** [comment]
Not at all.
Somehow I was under the impression that the convention of the project is to put all variable declarations at the top of a function.

**Comment by viciious** [comment]
Well, the convention is common sense :)
But generally I avoid declaring variables at the top of the function.

**Comment by Mark90** [comment]
Don't understand how this fixes it, but good work :p

I was also under the impression that C codebases generally keep their variable declarations at start of function to avoid compiler warnings.

**Pull request merged**
