### PR TITLE
Premake

### PR DESCRIPTION
**Pull request by stopiccot**
I've already made a proposal to use cmake as a crossplatform built tool to make maintenance much easier. After making some tests with cmake I once again realized how horrible it is. So I decided to use premake instead (http://industriousone.com/premake). It has nice declarative lua-based scripting and is very simple overall.

This branch is still work in progress but it would be great if you have time to take a look through the code and give some feedback and your overall impressions about this idea.

I've tested this on Windows 7 x64 (I used premake4.4-beta5 from http://industriousone.com/premake/download) and Ubuntu 13.10 x64 (premake4 from apt-get). On windows you need to run

```
 premake4 vs2010
```

in qfusion/source directory to generate visual studio projects (old project files are not removed yet). On linux

```
 premake4 gmake && make config=debug64
```

Known issues:
- no precompiled headers support in a way we need. There is no option in premake to ignore precompiled headers for specific files in project. It can be fixed with some refactoring.
- for now angelscript and librocket on linux should be prebuilt manually by calling make.
- currently no OS X support. But it seems to broken in master anyway

### CODE REVIEW

**Comment by stopiccot** [comment]
So did you have a chance to look through the code?

**Comment by viciious** [comment]
Hi Alexey,

no, not yet. At this stage when 1.1 is _almost_ finished I'm kinda cautious
to make any disruptive changes like this one.

2014/1/10 Alexey notifications@github.com

> So did you have a chance to look through the code?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/pull/57#issuecomment-31996794
> .

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Thats completely understandable. But actually I wasn't asking to merge my changes. I need your overall opinion and if possible to look through the code and find any flaws that I've missed so can fix them in branch. No merges right now.

**Comment by viciious** [comment]
ok, will do soon.

2014/1/11 Alexey notifications@github.com

> Thats completely understandable. But actually I wasn't asking to merge my
> changes. I need your overall opinion and if possible to look through the
> code and find any flaws that I've missed so can fix them in branch. No
> merges right now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/pull/57#issuecomment-32068743
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Alright, I kinda dig it but somehow I feel that requiring premake may be confusing for newcomers not to mention its shortcomings.. The necessity to manually make libRocket and angelscript isn't that much of a showstopper but still annoying. Precompiled headers do speed up UI compilation quite a bit, I'd rather not lose'em. In conclusion, I dunno whether the benefits of premake actually outweight its shortcomings.

**Pull request closed without merging**
