### PR TITLE
More efficient spectator drawing

### PR DESCRIPTION
**Pull request by hettoo**
Currently, spectators are drawn in three columns. The left is aligned left, the middle one is centered and the right is aligned at the right. On a wide screen, there can be a lot of horizontal space between these columns, and precious vertical space is easily lost due to the small number of columns.

I propose a more dynamic approach that tries to scale the number of columns according to the width of the names. All the columns will be aligned at their center.
The columns are assigned equal horizontal space based on the maximum name width. For instance, with 5 spectators the result may be this:
5 items
With 4 spectators, it could look like this:
4 items

Names are added outwards, starting from the middle column. If the number of columns is even, the counting is biased to the left:
5 items

Columns are positioned as close together as possible to improve readability:
3 items

The patch includes some refactoring.

### CODE REVIEW

**Comment by hettoo** [comment]
I made quite some changes to make it more visually pleasing; will post screenshots and explanation later.

**Comment by hettoo** [comment]
Let me just explain by example. :p
This is what the new code could do with 1-11 players:











Note that things can still be different based on the lengths of the names.
There will now always be symmetry.

The fifth example is quite ugly. In this case reducing the number of columns gives a too vertical configuration, so this is on the border of what is allowed. If there were 4 columns and 3 on the second row it would reduce the number of columns.
If there are at least two solid rows, I do not consider it ugly to have different alignment in the last row, as can be seen in the last example.

**Comment by viciious** [comment]
Looks good!

**Comment by hettoo** [comment]
Thank you. :)

Based on a suggestion I made another change that prefers vertical configurations if there will be at most three rows. I know I motivated at first by the need for optimizing vertical space, but three rows is not the end of the world, and it is easier on the eyes:






The other configurations are still as in the previous comment.
Note that the one I called "quite ugly" has also been improved here.

I'm done if this is ok. Alternatively, I could revert that last commit.

**Pull request merged**
