### PR TITLE
FTLIB i18n: Add lazy text rendering and fallback font support

### PR DESCRIPTION
**Pull request by Triang3l**

### CODE REVIEW

**Comment by Triang3l** [comment]
@viciious It renders 32-255, not 32-127. >127 characters are multi-byte.

**Comment by Triang3l** [comment]
But I think we don't need to always render the extended Latin character set, non-English scripts should be treated equally, no matter whether they're Latin or not.

**Comment by viciious** [comment]
we don't need to precache chars with code above 127, imo

**Comment by Triang3l** [comment]
The verification is done by GrabWChar and ftlib_draw.

**Pull request merged**
