### PR TITLE
Alt-Gr support in linux

### PR DESCRIPTION
**Pull request by kalhartt**
I can do this without adding a `K_ALTGR` key, but this was the cleanest solution imo.

### CODE REVIEW

**Comment by kalhartt** [comment]
I was under the impression that altgr symbols are currently working in windows, based only on reports from other players. I'll test it and see if I can connect `K_ALTGR`.

**Comment by viciious** [comment]
Alternatively, just remove K_ALTGR and pass keysym to XLateKey

**Comment by kalhartt** [comment]
I'll go with that suggestion. After looking at XLateKey in more detail, I don't know why we need it to return the key's char, seems like its a small check for a printable character and is completely unnecessary. So I took it out.

**Comment by viciious** [comment]
Is this 100% safe to merge now?

**Comment by kalhartt** [comment]
Absolutely!

**Comment by viciious** [comment]
Ok, thanks! :)

**Pull request merged**
